---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gh-actions-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
